### ISSUE TITLE
scroll event fires too late on mobile iOS Safari

### ISSUE THREAD

**Issue by sladex** [dinbror/blazy#10]
Scroll event is not fired until the scrolling action comes to a complete stop.
Handling `touchmove` event makes things significantly better:

    unbindEvent(window, 'touchmove', validateT);

An article about it:
http://tjvantoll.com/2012/08/19/onscroll-event-issues-on-mobile-browsers/

**Comment by jDeppen** [comment]
[Not fixed for Cordova web views](http://developer.telerik.com/featured/scroll-event-change-ios-8-big-deal/) :(

> One caveat for Cordova developers
>
> Although Apple implemented this change in iOS Safari, as well as its new WKWebView control, it did not change the scroll behavior in its old UIWebView control. And because of a major bug in the replacement WKWebView control, the Cordova team cannot upgrade to WKWebView yet.

> This means that at the moment Cordova apps running on iOS 8 continue to pause JavaScript execution, and will continue to until Cordova can upgrade. And this doesn’t just affect Cordova apps. Any iOS app that uses web views — including Facebook, Twitter, and Chrome for iOS — will get the old behavior until they upgrade their apps to WKWebView. So yes, that means you could get different behavior opening the same URL from different iOS apps depending on which API they use internally.

> Update (September 25th): Commenter Ben Kennedy found that, for whatever crazy reason, the old scroll behavior also applies to home screen web apps. So to summarize, apps that run in Safari or in a WKWebView get the new scroll behavior, apps that run in a UIWebView or in a home screen web app do not.

**Comment by dinbror** [comment]
Hey jDeppen.

Yes I noticed it in chrome for IOS. Thanks for the explanation.
