### ISSUE TITLE
Add a method to change options post initialisation

### ISSUE THREAD

**Issue by gajus** [dinbror/blazy#100]
Specifically, I'd like to be able to control the `offset` option after constructing `Blazy` instance.

**Comment by gajus** [comment]
The use case:

* Before `DOMContentLoaded` event, I want to use offset `0`.
* After, I want to increase to a different value.

**Comment by dinbror** [comment]
hey @gajus 

That's already possible. If you save blazy as a variable you can change the options on the variable whenever you want:

```
var bLazy = new Blazy();
...
bLazy.options.offset = 100;
```

**Comment by gajus** [comment]
@dinbror Thank you for pointing this out. I figured it eventually by looking at the source code, though I was expecting to see a setter. Controlling options in this manner can lead to all sorts of unexpected mutations.

**Comment by dinbror** [comment]
@gajus: yes it also isn't build for that. No setters to keep filesize small
