### ISSUE TITLE
Doesn't always load

### ISSUE THREAD

**Issue by mortenhjort** [dinbror/blazy#116]
I've got no idea why it seems the images loads quite randomly.
Try to reload this page a few times and you'll see it only works once in a while: http://mortenhjort.dk/synchub/

The behaviour is very random especially when testing in various browsers. And sorry if I'm in a error 40, but I've got no clue why its behaves as it does.

**Comment by dinbror** [comment]
Hej @mortenhjort 

Prøv at flytte dine script tags ned i bunden af body tagget. Tror problemet er at blazy bliver initialiseret inden siden er loadet færdig
