### ISSUE TITLE
getting problem in mozila firefox.

### ISSUE THREAD

**Issue by pawanchauhan05** [dinbror/blazy#118]
visit www.bardanatrade.tk in both chrome and firefox browser.
it is working fine in chrome but getting problem in firefox i.e. original images is not loaded instead of loading  icon is appearing.

**Comment by dinbror** [comment]
Hey @pawanchauhan05 

You're creating a new instance of blazy 4 times with the same selector "img". Instead only initialize it once, and call the public load function in the sliders callback

**Comment by dinbror** [comment]
@pawanchauhan05 

Friendly ping. Still having issues?

**Comment by dinbror** [comment]
closing due inactivity
