### ISSUE TITLE
Starts on scroll but not on load

### ISSUE THREAD

**Issue by jenstornell** [dinbror/blazy#120]
On my site the images are loaded when I scroll but not on load. Can I force trigger Blazy to load visible images on load as well?

**Comment by dinbror** [comment]
Hey @jenstornell
They should out of the box. Do you have a link so I can see?
There is a public function (revalidate) you can call but it shouldn't be needed.

**Comment by jenstornell** [comment]
It was probably some wierd image loading delay. A bit strange.

**Anyway, I ended up with an own plugin:**
https://github.com/jenstornell/img-defer.js

It's not lazy load, but it's loading the images after dom has loaded.
