### ISSUE TITLE
Opera Add Block blocking my images on website

### ISSUE THREAD

**Issue by naymapl** [dinbror/blazy#121]
Have no idea why opera blocking my images on my website but when I turn off it everything loading perfect.
 I use Multi-serve images option:
```
var bLazy=new Blazy({offset:300,breakpoints:[{width:420,src:"data-src-small"},{width:1024,src:"data-src-medium"}]});
```
On chrome with ublock and addblock or on safari and firefox everything runing well. Without blazy.js on opera everything runing well. Do you have any idea how to fix this issue ??

Link to website: https://nayma.eu/

Thanks a lot for any help with this.

**Comment by naymapl** [comment]
Ok - I found problem. The image what i preload has name 1x1.gif and opera block it. I change name of preloaded file for preloader.gif and everythin runing well. Thanks you ;)

**Comment by dinbror** [comment]
hey @naymaeu 

Very interesting :) Thanks for your update
