### ISSUE TITLE
How to set <img> src if the source is a broken link?

### ISSUE THREAD

**Issue by skylee91** [dinbror/blazy#122]
How to set <img> src if the source is a broken link?

**Comment by dinbror** [comment]
Hey @skylee91 

Could you please elaborate? What do you want to achieve? Do you want to set an alternative src when the actual src is broken?

**Comment by skylee91** [comment]
Yes, let say the actual src is broken, can we display a Image Not Found picture to user?

**Comment by dinbror** [comment]
@skylee91 You can already do it today in the error callback. Something like this:

```
var bLazy = new Blazy({ 
        error: function(ele, msg){
            ele.src = "not-found-image.jpg"  
        }
    });
```

I might add it as an option to define in next release

**Comment by skylee91** [comment]
Thanks. It helps a lot.
