### ISSUE TITLE
Question about breakpoint

### ISSUE THREAD

**Issue by benzon** [dinbror/blazy#123]
Hi,

Just wondering what the thought behind removing breakpoint is?

The reason I am asking is that’s it’s more relevant than ever, serving images that fit the browser view, instead of delivering bigger images then needed.

The way users use the internet today is very different than a few years back, they might start of in portrait mode, and then turn to landscape and if blazy was keeping abit track on this, you would be able to use different image sizes according to that if that makes sence?

That way bLazy would help quite a lot making sure you give the user the best experience in general, maybe even make it possible to set width and height for a breakpoint, so it fills out those html properties?

**Comment by dinbror** [comment]
Hey @benzon.

Why not use srcset and/or the picture element instead? Blazy also supports lazy load of these types. 
I want to keep the script as small as possible and my plan was to remove the breakpoint feature but since a lot of people are using it (e.g. for background images) I have keept it there

**Comment by dinbror** [comment]
Friendly ping @benzon. Can I close it?

**Comment by benzon** [comment]
Sure :)

Tried playing with srcset, and I can’t get it to work like intended with Blazy

Could you drop me a hint or two on this matter? It’s okay if your answer is Danish hehe.

**Comment by dinbror** [comment]
@benzon Ok :) Hvad er dit problem? Hvad er det du ikke kan få til at virke?
Har du set eksempel 1.4? http://dinbror.dk/blazy/examples/

**Comment by benzon** [comment]
Nok det jeg lige manglede, får lige kigget på det, har haft alt alt for travlt til lige og få svaret tilbage beklager jeg.
