### ISSUE TITLE
No image visible

### ISSUE THREAD

**Issue by chwakil** [dinbror/blazy#160]
Hi,
   I am loading data dynamically from PHP server. The data is similar to:

```
$output .= "<div class='item'>"
                . "<img class='b-lazy' src='common_images/loader.gif' width=" . $width . " height=" . $height . " data-src='" . $src . "' alt=/>"
                . '</div>'
        ;
```

I am using rowgrid to display data which is with scroll bar container. After receiving data I append data like this:

$(".container").append(data);
$(".container").rowGrid("appended");

Now when I do not use blazy images are displaying very well but with blazy no image is visible. Please help.

**Comment by kozie** [comment]
Care to share your solution since you seemed to have solved it yourself already, @chwakil ? ;)
