### ISSUE TITLE
Current project status

### ISSUE THREAD

**Issue by DanielRuf** [dinbror/blazy#176]
Hi, what is the current status of this project? Is it still actively maintained?

**Comment by NickLion** [comment]
Late, but maybe would be useful for some people — obviously, it's abandoned. IMHO, right now it's better to use [native lazy loading](https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#Images_and_iframes) or if older browser support is needed (which is likely) use something like [lazysizes](https://github.com/aFarkas/lazysizes) to get better support with IntersectionObserver if it's supported.

**Comment by amerikan** [comment]
I don't think this is maintained anymore, looks like the last time a commit was made was about **_4 years ago_** at the time of this comment. Here's a useful resource: https://web.dev/native-lazy-loading/

And here are additional js libraries that offer similar functionality that I found during my exploration:
- https://github.com/aFarkas/lazysizes (most popular)
- https://github.com/tuupola/lazyload
- https://github.com/verlok/vanilla-lazyload
