### ISSUE TITLE
Not working with older IE browsers versions 5 & 7

### ISSUE THREAD

**Issue by jodyshop** [dinbror/blazy#178]
I tried it with older versions of IE explorer and found it doesn't work with older **IE browser 5 & 7** the Debugger through an error: 

```
 var bLazy = new Blazy();
'Element' is undefined
```

How to fix?
Thank you

**Comment by eelke** [comment]
@jodyshop 

Not sure if you are serious or simply trolling, but in case.. the last stable release of MSIE 5 was [18 years ago](https://en.wikipedia.org/wiki/Internet_Explorer_5). 
MSIE7 reached it's end of life (finally) in 2016, with Microsoft no longer supporting it.

Requesting support for any JS library to support these browsers is useless, no (sane) developer will spend another minute of their precious time on these browsers.

**Comment by dinbror** [comment]
@jodyshop Blazy works in IE7+. No support for IE 5 and 6. I hope you're not serious about that 😄
