### ISSUE TITLE
CSS transitions don't work

### ISSUE THREAD

**Issue by joshribakoff** [dinbror/blazy#19]
Adding CSS transitions doesn't work, I'm using CSS from your example: http://dinbror.dk/blog/blazy/#Transitions

Seems like adding a CSS class with javascript prior to document.ready makes the browser immediately apply the finishing styles, skipping any transition (In Firefox at least). The two workarounds would be:

1 - Fire only on document.ready
2 - Apply a timeout to applying the "b-loaded" class:
```
setTimeout(function() {
                        ele.className = ele.className + ' ' + options.successClass;
                    }, 100);
```

Here's a simple test page that demonstrates this:

```html
<html>
<head>
    <script src="/jquery-ui-1.10.4/jquery-1.10.2.js"></script>
    <style>
        #foo {
            border:10px red solid;
            transition:border 5s ease-in-out;
        }
        #foo.bar {
            border:10px green solid;
        }
    </style>

</head>
<body>
    <div id="foo">foo</div>
    <script>
        $(document).ready(function() {
            var el = document.getElementById('foo');
            el.className = el.className + ' bar';
        });
    </script>
</body>
</html>
```
The document.ready is deterministic. It can be replaced with a timeout, which makes the animations *sometimes* work, and *sometimes* get skipped. Trying to apply the new class immediately always results in the animation being skipped.

**Comment by tortilaman** [comment]
I'm having a similar issue. I've tried various different ways of implementing the css, and even tried having jQuerydo it in the success callback through either css, fadeIn(), or show(), and none of them will show any transitions, it just pops in.

**Comment by dinbror** [comment]
Not an issue anymore
