### ISSUE TITLE
B-Lazy doesn't fire sometimes when page has been visited

### ISSUE THREAD

**Issue by lukedanielson** [dinbror/blazy#24]
Not sure what it happening, but in Chrome (35.0.1916.114) on a Mac OSX (10.9.2), visiting my site that I've already visited, and possibly cached, none of the b-lazy elements change, nor do the success or error events fire.  

If I press refresh, everything runs normally.  If I go up to the location bar and press enter it will load fine too.  Just sometimes when opening a new tab and typing in the url and hitting enter.

Wondering if anyone else is experiencing this, and/or it is a b-lazy issue, or something else.

FYI, here is my call to b-lazy:

```js
var bLazy = new Blazy({ 
	selector: '.b-lazy',
	offset: 180, // Loads images 180px before they're visible
	success: function(ele){
		// Image has loaded
		// Do your business here
		console.log('img loaded');
	},
	error: function(ele, msg){
		console.log('b-lazy error:' + msg);
		console.log(ele);
		if(msg === 'missing'){
			// Data-src is missing

		}
		else if(msg === 'invalid'){
			// Data-src is invalid
		}
	}
});
```

Here is where I'm experiencing the issue: http://staging.aspirebeverages.com (even clicking on this link for me is a case when it sometimes does not fire)

Any ideas?  Thanks in advance!

**Comment by philipgiuliani** [comment]
Same problem here. I did a temporary fix by initializing it like this:

```javascript
blazy = new Blazy();
setTimeout(blazy.revalidate, 100);
```

**Comment by dinbror** [comment]
Please try the new version, 1.3.0. It should fix it.

**Comment by philipgiuliani** [comment]
Already done and yes seems to work :)

dinbror <notifications@github.com> schrieb am Fr., 23. Jan. 2015 12:57:

**Comment by thomasdebruin** [comment]
Experiencing this problem on the 1.3.1 version, using the revalidate temp fix for now

**Comment by dinbror** [comment]
Hey Thomas. 

Can you elaborate a bit? How do you reproduce it? Do you have a live example?

**Comment by thomasdebruin** [comment]
I will try to extract a example from the project I'm working on (still in development) and put this online next week.

**Comment by landykos** [comment]
I also still have the same issue on the 1.3.1 version. It happens on Chrome on PC when you refresh a page either with F5 or with the browser button for refresh. It won't replace the images that are in the viewport. All other images that are not in view work as expected.

**Comment by thomasdebruin** [comment]
In my case: the first couple of images in the dom load, but not all of the visible ones, as soon as I scroll they all load.

**Comment by dinbror** [comment]
@landykos: do you have a live example?
I expect that you either initialize blazy before dom is ready or a lot of repainting is done

**Comment by landykos** [comment]
@dinbror currently only on local dev right now. I'll make sure and circle back once I have something up and running public facing. 
Thanks!

**Comment by thomasdebruin** [comment]
In my case it had nothing to do with blazy but the combination with the packery layout plugin. I changed my code to trigger blazy after the layout algoritm is finished, that's moment to decide which images are within the viewport (and need to be loaded). This fixed my issue.

**Comment by tarik916** [comment]
I had the same problem in Safari due to the load cache it uses when entering the URL or using the back button. Adding this jQuery on page load fixed it.

$(window).bind("pageshow", function(event) {
				    if (event.originalEvent.persisted) {
				        window.location.reload() 
				    }
				});

This was while using v1.4.0.

**Comment by michalzubkowicz** [comment]
This issue still exists on v1.8.0. When I press back button in newest Chrome on Galaxy S6 lazy load doesn't work until I scroll a bit.

**Comment by adkanojia** [comment]
Yep,
I'm using version 1.8.2 and same problem is still there.
Only loads images for first time and doesn't work on cached pages.

**Comment by dinbror** [comment]
hey @akashdeepkanojia. 

Do you also see the issue on my examples page (http://dinbror.dk/blazy/examples/)?
What browser and device do you see the issue on?

**Comment by adkanojia** [comment]
I'm using OS X El Capitan
Chrome Version 56.0.2924.87 (64-bit)

Your example is working just fine.

This is my code:
```
var bLazy = new Blazy({
    selector: '.container img',
    success: function(element){
        var parent = element.parentNode;
        parent.className = parent.className.replace(/\bloading\b/,'');
    },
    error: function(err){
        console.log('Error loading image.');
        console.log(err);
    }
});
```

If I add the following code at the end then my example works fine too:
`setTimeout(bLazy.revalidate, 100);`

What could be the issue?

**Comment by kaa4ever** [comment]
Same issue here as @adkanojia. I'm on macOS Sierra, Safari 11.0.

Examples also working fine, but the "fix" `setTimeout(bLazy.revalidate, 100);` is not working.

**Comment by mxhCodes** [comment]
I'm using this library in  combination with the Drupal integration (drupal.org/project/blazy) and can confirm this problem. Once I use minification of JS assets, this problem occurs. Without minification, it does not occur. I guess it's some sort of a timing problem.

Edit: Most probably related:
https://github.com/dinbror/blazy/issues/125
I'm going to continue commenting there.

**Comment by alouane** [comment]
I have the same issue with blazy, even sometimes setimeout for less than 500ms doesn't work, it turns out it's a body loading issue, so I added this line on the body element: `<body onload="new Blazy();">`, and it worked perfectly
