### ISSUE TITLE
Create NPM package

### ISSUE THREAD

**Issue by yoyurec** [dinbror/blazy#38]
In addition to Bower package i suggest to add other popular repository - NPM.
It would be nice for Node.js users and frontenders who uses Browserify!

**Comment by eerikson** [comment]
+1!

**Comment by yoyurec** [comment]
you can install NPM package from Git, temporary use my fork (it has **project.json**)
```
npm install yoyurec/blazy
```

**Comment by eerikson** [comment]
That's great, thank you for doing that.

**Comment by dinbror** [comment]
Thanks. Its added now

**Comment by yoyurec** [comment]
:+1:

**Comment by jDeppen** [comment]
Is this the current way to install then?
```
npm install dinbror/blazy --save
```

This didn't work:
```
npm install blazy --save
```
*'blazy' is not in the npm registry*
*You should bug the author to publish it (or use the name yourself!)*

NPM: [https://docs.npmjs.com/cli/publish](Publish a package)

Thanks

**Comment by digitalkaoz** [comment]
unfortuatnatly its not registered at npm @dinbror , this trick works: `npm install --save git://github.com/dinbror/blazy`

**Comment by yoyurec** [comment]
>unfortuatnatly its not registered at npm

in addition - it has no CommonJS wrapper, only AMD & global (`window`) ((

**Comment by dinbror** [comment]
@digitalkaoz, @jDeppen: Sorry about that. It is added now: 
```
npm install blazy --save
```

@yoyurec: Do you need support for commonjs? I only work with commonjs serverside. Do you use it on the client?

**Comment by yoyurec** [comment]
> Do you need support for commonjs?

it would be good

>Do you use it on the client?

yes, with [browserify](http://browserify.org/)

**Comment by jDeppen** [comment]
Thanks! And thank you for this library!

**Comment by dinbror** [comment]
>yes, with [browserify](http://browserify.org/)

Could you please test version 1.3.1 and see if everything is ok?

**Comment by yoyurec** [comment]
doesn't work for me ((
old version, with globals + my config = OK
new version, CommonJS + without config (default `.b-lazy` class) = OK
new version, CommonJS + my config = not OK :cry: 
```
'use strict';

var blazy = require('blazy');

        var blazyinit = new blazy({
            selector: .mySelector
        });
```
Looks like options doesn't pass to Blazy (works only your default).
1) i do wrong init
2) you didn't complete CommonJS module (wrapper on top changed, but code needs to be changed too)
