### ISSUE TITLE
Options to add images in array .

### ISSUE THREAD

**Issue by AbhishekNafdey** [dinbror/blazy#46]
Currently if we add images to DOM later on using say ajax, I will require to call the revalidate method.Suppose I already have the array of images due to some selector I had run or may be using directives .In this situation I can just pass the image element to the images array instead of asking for revalidate which reinitializes the plugin instance. 
Some kind of public method  will be of great help and would improve performance too.

 Blazy.prototype.updateImageList = function(img){
        images.push(img);
        count ++;
        validate();
    };

Also now as I have already added the images I can have the validate as a public method to be called after adding the images.
 Blazy.prototype.validate = function(){…

To enhance this further, suppose I am anyways selecting the images on the page to do some manipulation. So instead of asking the plugin to search the DOM again , I can just provide these selected array of elements as opion .
 function createImageArray(selector) { 
        if(options.imagesArr.length > 0){
             images = options.imagesArr;
             count = images.length;
         }else{
             var nodelist 	= document.querySelectorAll(selector);
             //converting nodelist to array
             count 			= nodelist.length;
             for(var i = count; i--; images.unshift(nodelist[i])){}
         }

	 }

Hope these help others as well and we can have them as a permanent feature for every one to take advantage of.

**Comment by dinbror** [comment]
Hey 	AbhishekNafdey.

Interesting idea, but I'm sure about how much it'll gain! You still need to find every image in the array in the DOM when you want to manipulate it

**Comment by dinbror** [comment]
Wont implement at the moment
