### ISSUE TITLE
Ability to check for un-loaded images and load from custom event?

### ISSUE THREAD

**Issue by benfrain** [dinbror/blazy#48]
Great plugin. Thanks.

I'm using it on a horizontal slider that uses transform3d to move things in the x axis. 
As this transforms the panels in the x axis via transform3d and then directly updates the scroll position, there is no scroll event fired and so bLazy doesn't load in the images that were off screen previously.

Is there a way of firing bLazy from a custom event to 're-check' which images are loaded and re-load as needed?

**Comment by dinbror** [comment]
Hey Ben.

Normally when I work with sliders they have a callback event in which I then forces the images sliding into view to load by calling the [public load function](http://dinbror.dk/blog/blazy/#Functions), bLazy.load(element, force);

**Comment by benfrain** [comment]
Ah, brilliant. That's exactly the thing I was after and missed it in the docs, thanks!
