### ISSUE TITLE
.load() doesn't work.

### ISSUE THREAD

**Issue by wdews** [dinbror/blazy#49]
Looks like the code the .load() function references is faulty. "loadImage()" simply doesn't work. At all. It's also unclear whether you pass it a jQuery object or a native DOM element. I've tried both, doesn't work with either.

**Comment by dinbror** [comment]
Hey.

That sounds odd. Do you have a live example? How're you using it? Show code or it didn't happend ;)

**Comment by DanielTate** [comment]
@wdews If you read the introduction it says it's NOT a jQuery plugin, this would force me to assume an HTML element is expected.

**Comment by Eworm** [comment]
I have the same question. It doesn't matter if I use:

bLazy.load(document.getElementsByClassName('highlight-item-img'), true);
or
bLazy.load($('.highlight-item-img'), true);

I always get the same error message:
Uncaught TypeError: i.getAttribute is not a function

**Comment by DanielTate** [comment]
@Eworm 
document.getElementsByClassName('highlight-item-img')
// [div.highlight-item-img]

returns an array even if its only one element

If you try 
bLazy.load(document.getElementsByClassName('highlight-item-img')[0], true);
// div.highlight-item-img

You need to pass in one element.

If you read the source you can see the function expects only ONE element.

Blazy.prototype.load = function(element, force){
		if(!isElementLoaded(element)) loadImage(element, force);
	};

**Comment by dinbror** [comment]
Fixed in v. 1.5.0, now you can pass a single element, a list of elements or jquery elements
