### ISSUE TITLE
Which is the true license?

### ISSUE THREAD

**Issue by shinnn** [dinbror/blazy#52]
http://dinbror.dk/blog/blazy/#license

> bLazy is licensed under the **DWIWYWBPVMS** license. (Do With It What You Want But Please Visit My Sponsor).

https://github.com/dinbror/blazy/tree/fae860857d58764d84222ef981305f0ea9c90b24#license

> MIT

**Comment by dinbror** [comment]
Both :)

**Comment by shinnn** [comment]
This project dual-licensed, right? And I recommend not using DWIWYWBPVMS license since it's a non-SPDX license. https://docs.npmjs.com/files/package.json#license
