### ISSUE TITLE
google chrome on android 4.3

### ISSUE THREAD

**Issue by crerem** [dinbror/blazy#53]
Hi,

I'm implementing Blazy on a wordpress theme and everything works fine until we tested on Android 4.3 - Chrome. The image loading is not firing when you scroll.

Same implementation works fine on IOS Safari on iphone, and on same android but the default browser.

Is it something i can do or do you know a fix ?
thanks

**Comment by ArmorDarks** [comment]
Tested on Android 4.3 Chrome — everything works. Can't confirm issue.

**Comment by dinbror** [comment]
@crerem : Do you have a live example?

@ArmorDarks : Thanks for testing.

**Comment by crerem** [comment]
Sorry - i deactivated the script. I would try to install it again and post here the link
Thanks

**Comment by dinbror** [comment]
Closed. Couldn't reproduce
