### ISSUE TITLE
Create few instance of Blazy on the same page

### ISSUE THREAD

**Issue by yuri1992** [dinbror/blazy#56]
Hi,
on the current pattern that you using its impossible to make few instance of Blazy on the same page,
the global variables images, options are shared between all instance of Blazy.
(I have different error/success scenario to handle)

**Comment by dinbror** [comment]
Hey @yuri1992 

I see. I'll look into it.

**Comment by dinbror** [comment]
Hey @yuri1992 - I solved it. I just need to test it properly so Im sure I haven't broken anything else.

**Comment by dinbror** [comment]
Fixed in 1.4.0

**Comment by yuri1992** [comment]
Thanks!
