### ISSUE TITLE
Compatibility with list.js

### ISSUE THREAD

**Issue by wolffe** [dinbror/blazy#58]
How would you make this plugin compatible with list.js?

https://github.com/javve/list.js

**Comment by dinbror** [comment]
Hey @wolffe.

It seems the listjs site is offline! But Im sure you can solve most of it be triggering the images you add to the list by using either .load or .revalidate --> http://dinbror.dk/blog/blazy/#Functions

**Comment by dinbror** [comment]
Feel free to reopen if you need more help
