### ISSUE TITLE
Add blazy on div scroll

### ISSUE THREAD

**Issue by LeG3nDz** [dinbror/blazy#59]
Hi,

I would like add Blazy on my page, but the scroll is not on my body, but on "big container" (<div id="container">.

So, blazy does not work because it must detect the scroll on the body.

Do you know how i can change this setting ?

Thank you ! :)

**Comment by dinbror** [comment]
Hey @LeG3nDz -

Use the container attribute: http://dinbror.dk/blog/blazy/#Inside

**Comment by dinbror** [comment]
Feel free to reopen if it doesn't solve your issue
