### ISSUE TITLE
Wrong src if angular.js used

### ISSUE THREAD

**Issue by tsamu** [dinbror/blazy#61]
1.
If you use data-src="{{ var }}"  you have to use (eg. jquery docready)
$(document).ready(function() {
var bLazy = new Blazy();
}

2.
data-src somehow initialize element.src, so images loaded before scope.load and
after var dataSrc = ele.getAttribute(source) || ele.getAttribute(options.src); 
dataSrc is this string: {[var}} (and not the value of the var)

It seems, that the problem is data-src attribute, because if I use this, it works well.
data-src2="{{var}}"
blazy.js
scope.options.src = source = options.src || 'data-src2';

I created a demo ( http://jsfiddle.net/ryo2vg88/3/ ), so it seems its an angular specific bug, and data-src is involved.

Anyway I report this issue https://github.com/angular/angular.js/issues/13081

**Comment by tsamu** [comment]
If i use ng-src instead of src offsetHeight = 0
Need force=true to load image:
if (force || (ele.offsetWidth > 0 && ele.offsetHeight > 0))

**Comment by dinbror** [comment]
hey @tsamu 
I see the issue. A workaround here and now is to change where the src is stored on an image. There is already an option for that called "src" (http://dinbror.dk/blog/blazy/#Options):

```
var bLazy = new Blazy({
   src: 'data-blazy'
});
```

**Comment by dinbror** [comment]
Closing the issue since it has nothing to do with blazy.js. I reported a new issue at angular since they closed yours
