### ISSUE TITLE
Uncaught TypeError: Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by lifeisfoo** [dinbror/blazy#63]
Using these code
```html
<script type="text/javascript" src="https://cdn.jsdelivr.net/blazy/1.4.1/blazy.min.js"></script>
<script>
    ;(function() {
        // Initialize
        var bLazy = new Blazy();
    })();
</script>
```
will thrown this error: ```Uncaught TypeError: Cannot read property 'error' of undefined```.
Even with no elements in use. Even with 1.4.0.

**Comment by dinbror** [comment]
Hey @lifeisfoo .
I see. The bug was introduced in version 1.4.0 and fixed in version 1.4.1. Sadly I didn't manage to update the minified version properly :( 
I have updated the minified version here at github and will release a new version soon.

Thanks for reporting

**Comment by lifeisfoo** [comment]
When you plan to release it (1.4.2?) on the CDN?
I'm building a website using it and I'm going live in days :).

Thank you for your work.

**Comment by dinbror** [comment]
Fixed in v. 1.5.0
