### ISSUE TITLE
Support for srcset?

### ISSUE THREAD

**Issue by voltronik** [dinbror/blazy#75]
Currently, when using srcset, I get the 'b-error' class added to my images. 
I've tried using `src: srcset` but this doesn't work as it removed the srcset tag completely. 

Is there are plans to integrate support for srcset or can you suggest another way to fix this? 

Thanks, 
Jack

**Comment by dinbror** [comment]
Hey @voltronik 

Yes it would make sense to support srcset.
Will look into it.

Thanks

**Comment by dinbror** [comment]
Implemented in v. 1.6.0
