### ISSUE TITLE
How to remove IE7 support

### ISSUE THREAD

**Issue by dantahoua** [dinbror/blazy#80]
Hello! As I am a size freak ;), I would like to know how to remove support for IE7 or even IE8 as you mentioned in the doc it could be removed...
"bLazy is lightweight, less than 1.2KB and less than 1.05KB if you don't need IE7- support." 
Thanks!

**Comment by dinbror** [comment]
hey @dantahoua 

Remove the querySelectorAll polyfill:

```
//IE7- fallback for missing querySelectorAll support
        if (!document.querySelectorAll) {
            var s = document.createStyleSheet();
            document.querySelectorAll = function(r, c, i, j, a) {
                a = document.all, c = [], r = r.replace(/\[for\b/gi, '[htmlFor').split(',');
                for (i = r.length; i--;) {
                    s.addRule(r[i], 'k:v');
                    for (j = a.length; j--;) a[j].currentStyle.k && c.push(a[j]);
                    s.removeRule(0);
                }
                return c;
            };
        }
```

Besides that we would have to rewrite some of the looping and stuff like that to optimize more.

**Comment by tomByrer** [comment]
> Besides that we would have to rewrite some of the looping and stuff like that to optimize more.

If someone would go through all that, might as well program in ES6 & transpile down as needed?

**Comment by dinbror** [comment]
I consider this "issue" fixed. Feel free to reopen if you disagree.
