### ISSUE TITLE
multiserve image loads only default

### ISSUE THREAD

**Issue by dgorges** [dinbror/blazy#82]
Image:
`<img class="bJS_lazy" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="default.jpg" data-src-small="default-small.jpg" alt="Image" />
`
js
`
var bLazy = new Blazy({
				breakpoints: [{
					width: 900
					, src: 'data-src-small'
				}]
				, selector: s.selector
				, offset: 350
				, successClass: 'b_loaded'
				, validateDelay: 10
			});
`
bLazy loads the data-src image (default.jpg) not the data-src-small. I tested it on different screen resolutions. From 300px to 2000px.

**Comment by in2lag** [comment]
Can somebody confirm this? Quite an issue

**Comment by dinbror** [comment]
@in2lag + @dgorges:

The breakpoints are based on screensize not browsersize:
https://github.com/dinbror/blazy/issues/77

**Comment by in2lag** [comment]
Thanks, i figured it out today, PR will be hopefully ready tomorrow ;)

**Comment by dinbror** [comment]
I'll add support for srcset and the picture element very soon

**Comment by dinbror** [comment]
Marked "breakpoints" as obsolete in version 1.6.0. Use srcset and/or the picture element instead
