### ISSUE TITLE
Images won't (always) load at all, without calling revalidate()

### ISSUE THREAD

**Issue by k03n00b** [dinbror/blazy#83]
Problem is that the latest version v1.5.4 - 2016.03.06 isn't always handle b-lazy selector-classes, when calling `new Blazy(...`

I'm using custom selector-class `.b_lazy`, if it matters.
Problem occurs occasionally when using latest Windows Chrome (Version 50.0.2661.75 m).

I'm not using jQuery, but script will wait DOM's ready via standard javascript: `document.addEventListener("DOMContentLoaded", init, false);`

Images will load after calling `revalidate()`.
So firstly I scheduled `revalidate()` after 1 second when bLazy was initialized and DOM was ready.
It solved the problem, but It's a bit hacky, so I decided rollback to v1.3.1 - 2015.02.01.
After rolling back, problem disappeared.

Sorry, that I didn't had time to debug this more detailed.

**Comment by dinbror** [comment]
Hey @k03n00b 

Thats odd. In latest version I'm wrapping the init function in a setTimeout to ensure it wont be called too early. Do you have a live example, jsfiddle or similar so I can digg into it?

Thanks

**Comment by k03n00b** [comment]
Thanks for the quick reply!
I'm afraid not. It's quite complex website and it wouldn't be easy to insulate the problem.
I think `setTimeout ` will do the trick as it did when we tested it.
