### ISSUE TITLE
Disallow multiple b-loaded classes -request

### ISSUE THREAD

**Issue by k03n00b** [dinbror/blazy#84]
Would it easy (and not too expensive) to implement, that bLazy would check if class already exists?
With (over)usage of revalidate will result multiple classes:
`b_loaded b_loaded b_loaded`

Thanks

**Comment by dinbror** [comment]
Hey @k03n00b 

What version are you using. It shouldn't be possible after version 1.5.x

**Comment by dinbror** [comment]
Friendly ping @k03n00b

**Comment by dinbror** [comment]
Ok I see it and will fix it. But I think its more important to fix the issue that you need to call revalidate right after init.

Have you only seen the load issue on page refresh?

**Comment by dinbror** [comment]
Fixed in version 1.6.0
