### ISSUE TITLE
About multi-serving background images

### ISSUE THREAD

**Issue by gausarts** [dinbror/blazy#86]
Thank you for the great plugin ;)

I have been integrating [Blazy](https://drupal.org/project/blazy) v1.5.4 below with [GridStack](https://drupal.org/project/GridStack) and [Slick carousel](https://drupal.org/project/slick), and probably more, and they are working nicely with multi-serving background images so far.

Having multi-serving background images for **particular purposes** such full screen carousels, or responsive grids is far more flexible than inline multi-serving images thanks to CSS background-size cover property.

I noticed the latest Blazy depreciated breakpoints.
I wonder and hope that the **multi-serving background images** feature will continue being supported in the upcoming releases?

Thanks.

**Comment by dinbror** [comment]
Hey @gausarts 

I actually planned to remove the breakpoints feature in next release and recommend start using srcset and/or the picture element instead but I see your case. Haven't thought about that so I guess breakpoints will stick around for a while anyways :)

**Comment by gausarts** [comment]
Thank you for considering it.

Perhaps Blazy v 2.0 is good to see it go so that people can decide to stick to pre 2, or post 2 release depending the feature they need?

If it must go some day, to keep it lean, hopefully you could consider providing at least an optional separate extension for backward compatibility to stick with it?

Thanks again.

**Comment by dinbror** [comment]
Roger
