### ISSUE TITLE
ES6 support ?

### ISSUE THREAD

**Issue by LeG3nDz** [dinbror/blazy#91]
Hi,

A media with babel is it possible? I've error when i run with blazy babel :)

**Comment by kamotos** [comment]
Not sure how your setup looks likes, but I use blazy with no issues using ES6  (babel/webpack)

**Comment by dinbror** [comment]
hey @LeG3nDz 

Can you elaborate a bit more? What error do you get? How is your setup? Any code to see?

**Comment by LeG3nDz** [comment]
Hi guys !

I've this error, after my `grunt babel` command : 

> Erreur : TypeError: p is undefined

My config :

`options: {
        sourceMap: true,
        presets: ['es2015'],
        compact: false
    },
    dist: {
        files: {
            '<%= config.publicJs %>': '<%= config.publicJs %>'
        }
    }`

Thank you !
