### ISSUE TITLE
Bugs of 'loadInvisible'.

### ISSUE THREAD

**Issue by chenkun24** [dinbror/blazy#95]
When an element is hidden, 'getBoundingClientRect' does not work, and images will load when the page was loaded.
Is it a bug? 
Is there any way to load hidden images while scrolling?

**Comment by dinbror** [comment]
hey @chenkun24 

Yes thats how getBoundingClientRect works. Instead of adding display:none to your container/image you could maybe use visibility: hidden or set height and width to zero?

**Comment by dinbror** [comment]
Closing it since it's a browser behavior. The browser doesn't bother rendering hidden items at all why they getBoundingClientRect and other just returns zero
